/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-container-lowest": "#060f15",
          "outline": "#988ca0",
          "on-primary-fixed": "#2c0051",
          "tertiary-fixed-dim": "#c8c5cd",
          "on-surface": "#dae4ec",
          "surface-container-low": "#131d23",
          "secondary-fixed": "#7df4ff",
          "on-error-container": "#ffdad6",
          "inverse-primary": "#8422dc",
          "on-tertiary-fixed": "#1b1b21",
          "inverse-on-surface": "#283238",
          "surface-variant": "#2c363d",
          "secondary-fixed-dim": "#00dbe9",
          "on-tertiary-fixed-variant": "#47464d",
          "primary": "#dcb8ff",
          "surface-container": "#172127",
          "surface": "#0b151a",
          "on-primary-fixed-variant": "#6700b5",
          "background": "#0b151a",
          "error-container": "#93000a",
          "surface-dim": "#0b151a",
          "on-primary": "#480081",
          "primary-fixed-dim": "#dcb8ff",
          "on-surface-variant": "#cfc2d7",
          "tertiary-container": "#64636a",
          "on-secondary-fixed": "#002022",
          "surface-container-highest": "#2c363d",
          "on-tertiary-container": "#e3e0e8",
          "primary-fixed": "#efdbff",
          "secondary-container": "#00eefc",
          "outline-variant": "#4c4354",
          "surface-tint": "#dcb8ff",
          "inverse-surface": "#dae4ec",
          "surface-container-high": "#222b32",
          "on-secondary": "#00363a",
          "error": "#ffb4ab",
          "on-tertiary": "#303036",
          "tertiary": "#c8c5cd",
          "primary-container": "#8a2be2",
          "surface-bright": "#313a41",
          "on-secondary-fixed-variant": "#004f54",
          "tertiary-fixed": "#e4e1ea",
          "secondary": "#d3fbff",
          "on-background": "#dae4ec",
          "on-secondary-container": "#00686f",
          "on-error": "#690005",
          "on-primary-container": "#eed9ff"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "container-margin": "32px",
          "gutter": "20px",
          "xl": "40px",
          "unit": "4px",
          "xs": "4px",
          "lg": "24px",
          "sm": "8px",
          "md": "16px"
      },
      "fontFamily": {
          "headline-md": ["Space Grotesk", "sans-serif"],
          "label-caps": ["Space Grotesk", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "headline-lg": ["Space Grotesk", "sans-serif"],
          "display-xl": ["Space Grotesk", "sans-serif"]
      },
      "fontSize": {
          "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
          "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "display-xl": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
