#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
//  Razorpay one-time setup.
//  ───────────────────────────────────────────────────────────────────────
//  1. Put your Razorpay API keys in discord-bot/.env:
//        RAZORPAY_KEY_ID=rzp_test_...      (Test mode first)
//        RAZORPAY_KEY_SECRET=...
//  2. Run:  node scripts/razorpay-setup.js
//
//  It creates the four subscription plans the bot sells (Pro and Server,
//  monthly and yearly, at the rupee prices in plans.js) — or finds them if a
//  previous run already did — generates the two secrets the bot needs, and
//  writes everything to discord-bot/.env.render (git-ignored), ready to paste
//  into Render → Environment. It never prints a secret.
//
//  Safe to run again: plans are matched by name and amount, secrets are kept.
// ═══════════════════════════════════════════════════════════════════════════

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { PLANS } = require('../plans');

const BOT = path.join(__dirname, '..');
const ENV_FILE = path.join(BOT, '.env');
const OUT_FILE = path.join(BOT, '.env.render');

function readEnvFile(file) {
  if (!fs.existsSync(file)) return {};
  const out = {};
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m) out[m[1]] = m[2].replace(/\s+#.*$/, '').trim();
  }
  return out;
}

const env = { ...readEnvFile(ENV_FILE), ...process.env };
const previous = readEnvFile(OUT_FILE);
const keyId = (env.RAZORPAY_KEY_ID || '').trim();
const keySecret = (env.RAZORPAY_KEY_SECRET || '').trim();

if (!keyId || !keySecret) {
  console.error('Put RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET in discord-bot/.env first (Razorpay Dashboard → Account & Settings → API Keys).');
  process.exit(1);
}
const mode = keyId.startsWith('rzp_live_') ? 'LIVE' : keyId.startsWith('rzp_test_') ? 'TEST' : 'UNKNOWN';

const auth = `Basic ${Buffer.from(`${keyId}:${keySecret}`).toString('base64')}`;
async function api(method, url, body) {
  const res = await fetch(`https://api.razorpay.com/v1${url}`, {
    method,
    headers: { Authorization: auth, 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`Razorpay ${res.status}: ${data?.error?.description || 'request failed'}`);
  return data;
}

// What the bot sells by subscription. Lifetime is a one-off payment link the
// bot makes per buyer, so it needs no plan.
const WANT = [
  { env: 'RAZORPAY_PLAN_PRO', name: 'GameGuide Pro (monthly)', period: 'monthly', paise: PLANS.pro.inr * 100 },
  { env: 'RAZORPAY_PLAN_PRO_YEARLY', name: 'GameGuide Pro (yearly)', period: 'yearly', paise: PLANS.pro.yearly.inr * 100 },
  { env: 'RAZORPAY_PLAN_SERVER', name: 'GameGuide Server (monthly)', period: 'monthly', paise: PLANS.server.inr * 100 },
  { env: 'RAZORPAY_PLAN_SERVER_YEARLY', name: 'GameGuide Server (yearly)', period: 'yearly', paise: PLANS.server.yearly.inr * 100 },
];

(async () => {
  console.log(`Razorpay ${mode} mode`);
  let existing = [];
  try {
    existing = (await api('GET', '/plans?count=100')).items || [];
  } catch (e) {
    console.error(`Could not reach Razorpay with these keys: ${e.message}`);
    process.exit(1);
  }

  const ids = {};
  for (const w of WANT) {
    const hit = existing.find(p => p?.item?.name === w.name && p?.item?.amount === w.paise && p?.period === w.period && p?.interval === 1);
    if (hit) {
      ids[w.env] = hit.id;
      console.log(`  found   ${w.name.padEnd(28)} ₹${(w.paise / 100).toLocaleString('en-IN')}  ${hit.id}`);
      continue;
    }
    const plan = await api('POST', '/plans', {
      period: w.period,
      interval: 1,
      item: { name: w.name, amount: w.paise, currency: 'INR', description: 'GameGuide-AI Discord bot' },
      notes: { gameguide_plan: w.env },
    });
    ids[w.env] = plan.id;
    console.log(`  created ${w.name.padEnd(28)} ₹${(w.paise / 100).toLocaleString('en-IN')}  ${plan.id}`);
  }

  // Secrets the bot needs; kept across runs so the webhook never has to change.
  const webhookSecret = previous.RAZORPAY_WEBHOOK_SECRET || crypto.randomBytes(24).toString('hex');
  const upgradeSecret = previous.UPGRADE_LINK_SECRET || env.UPGRADE_LINK_SECRET || crypto.randomBytes(32).toString('hex');

  const lines = [
    `# Generated by scripts/razorpay-setup.js (${mode} mode) — paste into Render → gameguide-bot → Environment.`,
    '# Git-ignored. Do not commit or share this file.',
    `RAZORPAY_KEY_ID=${keyId}`,
    `RAZORPAY_KEY_SECRET=${keySecret}`,
    `RAZORPAY_WEBHOOK_SECRET=${webhookSecret}`,
    ...WANT.map(w => `${w.env}=${ids[w.env]}`),
    `UPGRADE_LINK_SECRET=${upgradeSecret}`,
  ];
  // Keep anything else already in the file (the review sign-in, for example).
  const written = new Set(lines.map(l => l.split('=')[0]));
  for (const [k, v] of Object.entries(previous)) if (!written.has(k)) lines.push(`${k}=${v}`);
  lines.push('');
  fs.writeFileSync(OUT_FILE, lines.join('\n'), { mode: 0o600 });
  console.log(`\nWrote ${path.relative(process.cwd(), OUT_FILE) || OUT_FILE} — ${lines.length - 3} values for Render.`);
  console.log('The webhook secret to type into Razorpay is RAZORPAY_WEBHOOK_SECRET in that file.');
})().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
